#include "hook.hpp"
#include "sound.hpp"
#include "unicode_utils.hpp"
#include "win32_input.hpp"

namespace emebalachat {

KeyboardHook* KeyboardHook::s_instance = nullptr;

KeyboardHook::KeyboardHook(AppConfig& config, PipelineWorker& worker, FloatingBadge& badge, SystemTray& tray)
    : config_(config), worker_(worker), badge_(badge), tray_(tray) {
    s_instance = this;
    hReadyEvent_ = ::CreateEventW(nullptr, TRUE, FALSE, nullptr);
}

KeyboardHook::~KeyboardHook() {
    Stop();
    if (s_instance == this) {
        s_instance = nullptr;
    }
    if (hReadyEvent_) {
        ::CloseHandle(hReadyEvent_);
        hReadyEvent_ = nullptr;
    }
}

bool KeyboardHook::Start() {
    if (running_.exchange(true)) {
        return true;
    }

    if (hReadyEvent_) {
        ::ResetEvent(hReadyEvent_);
    }

    thread_ = std::thread(&KeyboardHook::HookThreadProc, this);

    if (hReadyEvent_) {
        ::WaitForSingleObject(hReadyEvent_, 2000);
    }

    return hHook_ != nullptr;
}

void KeyboardHook::Stop() {
    if (!running_.exchange(false)) {
        return;
    }

    if (hook_thread_id_ != 0) {
        ::PostThreadMessageW(hook_thread_id_, WM_QUIT, 0, 0);
    }

    if (thread_.joinable()) {
        thread_.join();
    }
}

void KeyboardHook::SetActive(bool active) {
    if (is_active_.exchange(active) != active) {
        badge_.SetStatus(active ? BadgeStatus::Active : BadgeStatus::Disabled);
        tray_.UpdateStatus(
            active,
            config_.engine_type == "auto" ? "Google Translate (Auto)" : config_.engine_type,
            config_.source_language,
            config_.target_language,
            config_.auto_send,
            config_.sound_enabled,
            badge_.IsVisible()
        );
        if (active) {
            PlayToggleOn();
        } else {
            PlayToggleOff();
        }
    }
}

void KeyboardHook::ToggleActive() {
    SetActive(!is_active_.load());
}

void KeyboardHook::CycleTargetLanguage() {
    std::string next_tgt = config_.CycleLanguage();
    badge_.SetLanguages(ToUtf16(config_.source_language), ToUtf16(next_tgt));
    tray_.UpdateStatus(
        is_active_.load(),
        config_.engine_type == "auto" ? "Google Translate (Auto)" : config_.engine_type,
        config_.source_language,
        next_tgt,
        config_.auto_send,
        config_.sound_enabled,
        badge_.IsVisible()
    );
    PlayLangChange();
}

void KeyboardHook::ToggleAutoSend() {
    config_.auto_send = !config_.auto_send;
    config_.SaveToFile();
    tray_.UpdateStatus(
        is_active_.load(),
        config_.engine_type == "auto" ? "Google Translate (Auto)" : config_.engine_type,
        config_.source_language,
        config_.target_language,
        config_.auto_send,
        config_.sound_enabled,
        badge_.IsVisible()
    );
    PlayModeChange();
}

void KeyboardHook::HookThreadProc() {
    hook_thread_id_ = ::GetCurrentThreadId();
    HINSTANCE hInst = ::GetModuleHandleW(nullptr);

    hHook_ = ::SetWindowsHookExW(
        WH_KEYBOARD_LL,
        KeyboardHook::LowLevelKeyboardProc,
        hInst,
        0
    );

    if (hReadyEvent_) {
        ::SetEvent(hReadyEvent_);
    }

    if (!hHook_) {
        running_.store(false);
        return;
    }

    MSG msg = {};
    while (::GetMessageW(&msg, nullptr, 0, 0) > 0) {
        ::TranslateMessage(&msg);
        ::DispatchMessageW(&msg);
    }

    if (hHook_) {
        ::UnhookWindowsHookEx(hHook_);
        hHook_ = nullptr;
    }
}

LRESULT CALLBACK KeyboardHook::LowLevelKeyboardProc(int nCode, WPARAM wParam, LPARAM lParam) {
    if (nCode != HC_ACTION || !s_instance) {
        return ::CallNextHookEx(nullptr, nCode, wParam, lParam);
    }

    const auto* kbd = reinterpret_cast<const KBDLLHOOKSTRUCT*>(lParam);

    // Completely bypass all synthetic inputs generated by Emebalachat
    if (kbd->dwExtraInfo == EXTRA_INFO_MARKER) {
        return ::CallNextHookEx(nullptr, nCode, wParam, lParam);
    }

    if (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN) {
        bool ctrl = (::GetAsyncKeyState(VK_CONTROL) & 0x8000) != 0;
        bool shift = (::GetAsyncKeyState(VK_SHIFT) & 0x8000) != 0;
        bool alt = (::GetAsyncKeyState(VK_MENU) & 0x8000) != 0;
        bool win = ((::GetAsyncKeyState(VK_LWIN) & 0x8000) != 0) || ((::GetAsyncKeyState(VK_RWIN) & 0x8000) != 0);

        // Always let Alt or Win key combinations pass through immediately
        // (preserves Excel newline Alt+Enter, game fullscreen Alt+Enter, Win shortcuts, etc.)
        if (alt || win) {
            return ::CallNextHookEx(nullptr, nCode, wParam, lParam);
        }

        // F9 hotkeys
        if (kbd->vkCode == VK_F9) {
            if (!ctrl && !shift) {
                s_instance->ToggleActive();
                return 1;
            } else if (ctrl && !shift) {
                s_instance->CycleTargetLanguage();
                return 1;
            }
        }

        // Enter keystroke interception
        if (kbd->vkCode == VK_RETURN) {
            if (ctrl && shift) {
                // Ctrl+Shift+Enter toggles Auto-Send mode
                s_instance->ToggleAutoSend();
                return 1;
            }

            if (ctrl) {
                // Ctrl+Enter is normal pass-through
                return ::CallNextHookEx(nullptr, nCode, wParam, lParam);
            }

            // Regular Enter or Shift+Enter
            if (!s_instance->IsActive()) {
                return ::CallNextHookEx(nullptr, nCode, wParam, lParam);
            }

            if (s_instance->worker_.IsBusy()) {
                // Worker is currently performing translation, let Enter pass through
                return ::CallNextHookEx(nullptr, nCode, wParam, lParam);
            }

            // Post task to worker and intercept Enter from reaching target control
            if (s_instance->worker_.PostTask(shift)) {
                return 1; // Intercepted immediately (< 1ms)!
            }
        }
    }

    return ::CallNextHookEx(nullptr, nCode, wParam, lParam);
}

} // namespace emebalachat
